### ISSUE TITLE
jsonschema.exceptions._RefResolutionError: hypothesis-jsonschema does not fetch remote references

### ISSUE THREAD

**Issue by nbro10** [python-jsonschema/hypothesis-jsonschema#109]
My understanding is that we can refer to other local JSON schemas using `$ref`. So, I have these 2 schemas in my local file system (in the same directory)

`main.json`

```
{
    "type": "object",
    "properties": {
        "language": {
            "$ref": "./language.json#"
        },
        "required": [
            "language",
        ],
        "additionalProperties": false
    }
}
```

And `language.json`

```
{
    "type": "string",
    "enum": [
        "en",
        "fr"
    ]
}
```

Now, I was trying to generate a random sample by calling `from_schema(my_schema).example()`, but I keep getting the error 

```
jsonschema.exceptions._RefResolutionError: hypothesis-jsonschema does not fetch remote references (uri='./language.json')
```

and I'm not sure why.

Instead of `"./language.json#"`, I also tried `"language.json#"` and other variations I've seen on the web...

Does this library support this? If yes, how? If not, what alternative do you suggest?

**Comment by Zac-HD** [comment]
A "remote reference" is anything outside the current document, so unfortunately this is working as intended - local filesystem and remote URL both involve IO, and that's the problematic part.

**Comment by Zac-HD** [comment]
IO and state make managing the logic much more difficult, introduce performance issues, and make caching unsafe.  I'd suggest resolving the schema into a single document before handing that to `hypothesis-jsonschema`.

**Comment by roversch** [comment]
Hey I totally understand where you're coming from @Zac-HD , but can you add a note somewhere? I just lost 2 hours before I stumbled upon this issue.

> As of version 0.11, this includes resolving non-recursive references!

This signals that `$ref` into other file is supported.

Anyway, thanks for the great library!
